### ISSUE TITLE
Adding the ability for the front end to prompt authorisation

### ISSUE THREAD

**Issue by gavinhenderson** [agorf/what2read#3]
Awesome project! Setup was really easy.

Is there any plan to add some kind of authorisation through the front end? So that I can host it then share it with my family and friends (without having to have them as friends on goodreads)?

I am assuming that this would be a large piece of work because it would mean generating the books during server runtime rather than in an automated script?

**Comment by agorf** [comment]
Hi @gavinhenderson Thanks for your kind words.

Could you explain some more your use case?

You are right that currently authorization is done through the command line but it's a one-time process to get the right credentials. After that, you can specify any user id you're friends with (or your own, of course) and the program should be able to import their (or your) library.

**Comment by gavinhenderson** [comment]
My use case would be, hosting this then sharing it with my friends and family who will be able enter their own userIds as I am connected with them on GoodReads. However, my friends and family would likely want tot share it on further but then it wouldn't work as I wouldn't be connected with these further people. So ideally users would be able to auth through a portal that would then allow them to generate results for themselves. Meaning that the project can be hosted and shared around easily to non technical users

**Comment by agorf** [comment]
@gavinhenderson Yeah that entails taking this project and implementing a web service based on it (SaaS). You are right this would mean a lot of work (probably a different kind of project).
